# Generated by Django 6.1.1 on 2026-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(blank=True, choices=[('TMONEY', 'TMONEY'), ('FLOOZ', 'FLOOZ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paygate_tx_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
